"""Added_learning_model

Revision ID: 92ae2eb941d2
Revises: 
Create Date: 2023-11-26 19:11:23.183165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ae2eb941d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create serializers if not exists cdp_tables')
    op.create_table('learning',
    sa.Column('associate_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('learning_resource', sa.String(length=255), nullable=False),
    sa.Column('resource_link', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cdp_tables'
    )
    op.create_index('idx_learning_associate_id', 'learning', ['associate_id'], unique=False, schema='cdp_tables')
    op.create_index('idx_learning_email', 'learning', ['email'], unique=False, schema='cdp_tables')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_learning_email', table_name='learning', schema='cdp_tables')
    op.drop_index('idx_learning_associate_id', table_name='learning', schema='cdp_tables')
    op.drop_table('learning', schema='cdp_tables')
    op.execute('drop serializers if exists cdp_tables')
    # ### end Alembic commands ###
